### ISSUE TITLE
Uncaught ReferenceError: particlesJS is not defined 

### ISSUE THREAD

**Issue by rav-redchamps** [magespices/mage2dark#1]
There is below js error in browser console 

Uncaught ReferenceError: particlesJS is not defined at app.js:1

and app.js file is being referenced from here https://mage2dark.net/js/app.js

### Preconditions

Magento Version: 2.3.3

Environment: Default

Third party modules: None

### Steps to reproduce

1. Make sure "Show slid box" setting is set to Yes
2. Go to any admin page and see browser console for error

**Comment by magespices** [comment]
There was an issue with the footer of the iFrame visible in the slideBox.
It's removed now. Issue should no longer be there.
