### ISSUE TITLE
Problem with Background colour &icon visibility in orders grid

### ISSUE THREAD

**Issue by rav-redchamps** [magespices/mage2dark#3]
### Preconditions

Magento Version: 2.3.3 CE

Environment: Developer

Third party modules: No

### Steps to reproduce

1. Go to Sales > Orders 
2. Scroll through order list till the time top toolbar becomes sticky
3. Notice the sticky toolbar color and icons visibility 

### Expected result

1. Correct background color and icon visibility

### Actual result

![orders](https://user-images.githubusercontent.com/5336201/70646618-4b62ca80-1c6d-11ea-84d6-5d00f7305f05.png)

**Comment by jakwinkler** [comment]
Acknowledged, however we can start working on this next week :-)

**Comment by jakwinkler** [comment]
Fix have been uploaded to 1.1.1 version.
